### ISSUE TITLE
Panorama Zooming

### ISSUE THREAD

**Issue by Kletterer** [amosproj/amos-ss2021-3d-viewer#8]
## User story
1. As a user
2. I want to use the mouse wheel
3. so I can magnify the center of my current view

## Acceptance criteria
* Zooming only possible in a reasonable range. Limit the range, such that picture does not look "pixeled"
* intuitivity: zoom in a reasonable speed
* after zoom in, zoom out also needs to be possible
* rotating the mouse wheel up means zoom-in, rotating the mouse wheel down means zoom-out
* Rotation is done in accordance to zoom level (when zoomed in, rotation speed is slower than when zoomed out)

## Definition of done
* Added only after week 5
* The same for all features

**Comment by leonopulos** [comment]
This feature is currently already implemented, but:

a) Still has a little bug, that I already quickly described in issue [21](https://github.com/amosproj/amos-ss2021-3d-viewer/issues/21)
Basically, the static value of 0.2 in the ´onPointerMove´ function in main.js lines 93-94 is the problem. This value needs to be higher/lower depending on whether the user is further zoomed in our out (so fov value higher or lower).

b) Will have to be altered as part of issue [#19](https://github.com/amosproj/amos-ss2021-3d-viewer/issues/19)
That is because currently the fov value is managed only inside the ´onDocumentMouseWheel´ function, but once a ´ViewerViewState´ object is introduced, that stores the current fov, the value will be available via the property of that object.
=> So the implementation of this issue might need to be changed a little, once #19 is done. But for now things can be worked on completely separately. Should the two implementations not properly work together, I will resolve that as release manager.
